[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
casey = "0.3"
paste = "1"
const-str = { version = "0.4", features = ["case"] }
yew = { git = "https://github.com/yewstack/yew.git", features = ["csr"] }

[build-dependencies]
walkdir = "2"
